name: deploy-site
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install mkdocs mkdocs-material mkdocs-roamlinks-plugin mkdocs-mermaid2-plugin
      - run: mkdocs build
      - name: Deploy to gh-pages
        run: |
          cd site
          git init
          git checkout -b gh-pages
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "deploy"
          git push -f "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
